<?php
//put the file into a variable
	$usernameFile = 'gamestats/username.txt';
	$xpFile = 'gamestats/xp.txt';
	$progressFile = './progress.txt';
	$Dmg1File = 'gamestats/dmg1.txt';
	$Dmg2File = 'gamestats/dmg2.txt';
	$Dmg3File = 'gamestats/dmg3.txt';
	$Dmg4File = 'gamestats/dmg4.txt';
	$Dmg5File = 'gamestats/dmg5.txt';
	$Shd1File = 'gamestats/shd1.txt';
	$Shd2File = 'gamestats/shd2.txt';
	$Shd3File = 'gamestats/shd3.txt';
	$Shd4File = 'gamestats/shd4.txt';
	$Shd5File = 'gamestats/shd5.txt';
	$Hth1File = 'gamestats/hth1.txt';
	$Hth2File = 'gamestats/hth2.txt';
	$Hth3File = 'gamestats/hth3.txt';
	$HthNShd1File = 'gamestats/hthnshd1.txt';
	$HthNShd2File = 'gamestats/hthnshd2.txt';
	$HthNShd3File = 'gamestats/hthnshd3.txt';
	$HthNShd4File = 'gamestats/hthnshd4.txt';
	$HthNShd5File = 'gamestats/hthnshd5.txt';
	$HthNShd6File = 'gamestats/hthnshd6.txt';
	$HthStl1File = 'gamestats/hthstl1.txt';
	$HthStl2File = 'gamestats/hthstl2.txt';
	$HthStl3File = 'gamestats/hthstl3.txt';
	$HthStl4File = 'gamestats/hthstl4.txt';
	$HthStl5File = 'gamestats/hthstl5.txt';
	$ShdStl1File = 'gamestats/shdstl1.txt';
	$ShdStl2File = 'gamestats/shdstl2.txt';
	$ShdStl3File = 'gamestats/shdstl3.txt';
	$ShdStl4File = 'gamestats/shdstl4.txt';
	$ShdStl5File = 'gamestats/shdstl5.txt';
	$ReverseFile = 'gamestats/reverse.txt';
	$Eng1File = 'gamestats/eng1.txt';
	$Eng2File = 'gamestats/eng2.txt';
	$MultX2File = 'gamestats/multx2.txt';
	$MultX3File = 'gamestats/multx3.txt';
	$MultX4File = 'gamestats/multx4.txt';
//get the contents of that file and put them into a variable for use
	$username = (string) file_get_contents($usernameFile);
	$xp = (int) file_get_contents($xpFile);
	$progress = (int) file_get_contents($progressFile);
	$Dmg1 = (int) file_get_contents($Dmg1File);
	$Dmg2 = (int) file_get_contents($Dmg2File);
	$Dmg3 = (int) file_get_contents($Dmg3File);
	$Dmg4 = (int) file_get_contents($Dmg4File);
	$Dmg5 = (int) file_get_contents($Dmg5File);
	$Shd1 = (int) file_get_contents($Shd1File);
	$Shd2 = (int) file_get_contents($Shd2File);
	$Shd3 = (int) file_get_contents($Shd3File);
	$Shd4 = (int) file_get_contents($Shd4File);
	$Shd5 = (int) file_get_contents($Shd5File);
	$Hth1 = (int) file_get_contents($Hth1File);
	$Hth2 = (int) file_get_contents($Hth2File);
	$Hth3 = (int) file_get_contents($Hth3File);
	$HthNShd1 = (int) file_get_contents($HthNShd1File);
	$HthNShd2 = (int) file_get_contents($HthNShd2File);
	$HthNShd3 = (int) file_get_contents($HthNShd3File);
	$HthNShd4 = (int) file_get_contents($HthNShd4File);
	$HthNShd5 = (int) file_get_contents($HthNShd5File);
	$HthNShd6 = (int) file_get_contents($HthNShd6File);
	$HthStl1 = (int) file_get_contents($HthStl1File);
	$HthStl2 = (int) file_get_contents($HthStl2File);
	$HthStl3 = (int) file_get_contents($HthStl3File);
	$HthStl4 = (int) file_get_contents($HthStl4File);
	$HthStl5 = (int) file_get_contents($HthStl5File);
	$ShdStl1 = (int) file_get_contents($ShdStl1File);
	$ShdStl2 = (int) file_get_contents($ShdStl2File);
	$ShdStl3 = (int) file_get_contents($ShdStl3File);
	$ShdStl4 = (int) file_get_contents($ShdStl4File);
	$ShdStl5 = (int) file_get_contents($ShdStl5File);
	$Reverse = (int) file_get_contents($ReverseFile);
	$Eng1 = (int) file_get_contents($Eng1File);
	$Eng2 = (int) file_get_contents($Eng2File);
	$MultX2 = (int) file_get_contents($MultX2File);
	$MultX3 = (int) file_get_contents($MultX3File);
	$MultX4 = (int) file_get_contents($MultX4File);
//get the current info from unity and put them into a variable
	$curUsername = (string) $_POST("usernameKey");
	$curXp = (int) $_POST("xpKey");
	$curProgress = (int) $_POST("progressKey");
	$curDmg1 = (int) $_POST("Dmg1Key");
	$curDmg2 = (int) $_POST("Dmg2Key");
	$curDmg3 = (int) $_POST("Dmg3Key");
	$curDmg4 = (int) $_POST("Dmg4Key");
	$curDmg5 = (int) $_POST("Dmg5Key");
	$curShd1 = (int) $_POST("Shd1Key");
	$curShd2 = (int) $_POST("Shd2Key");
	$curShd3 = (int) $_POST("Shd3Key");
	$curShd4 = (int) $_POST("Shd4Key");
	$curShd5 = (int) $_POST("Shd5Key");
	$curHth1 = (int) $_POST("Hth1Key");
	$curHth2 = (int) $_POST("Hth2Key");
	$curHth3 = (int) $_POST("Hth3Key");
	$curHthNShd1 = (int) $_POST("HthNShd1Key");
	$curHthNShd2 = (int) $_POST("HthNShd2Key");
	$curHthNShd3 = (int) $_POST("HthNShd3Key");
	$curHthNShd4 = (int) $_POST("HthNShd4Key");
	$curHthNShd5 = (int) $_POST("HthNShd5Key");
	$curHthNShd6 = (int) $_POST("HthNShd6Key");
	$curHthStl1 = (int) $_POST("HthStl1Key");
	$curHthStl2 = (int) $_POST("HthStl2Key");
	$curHthStl3 = (int) $_POST("HthStl3Key");
	$curHthStl4 = (int) $_POST("HthStl4Key");
	$curHthStl5 = (int) $_POST("HthStl5Key");
	$curShdStl1 = (int) $_POST("ShdStl1Key");
	$curShdStl2 = (int) $_POST("ShdStl2Key");
	$curShdStl3 = (int) $_POST("ShdStl3Key");
	$curShdStl4 = (int) $_POST("ShdStl4Key");
	$curShdStl5 = (int) $_POST("ShdStl5Key");
	$curReverse = (int) $_POST("ReverseKey");
	$curEng1 = (int) $_POST("Eng1Key");
	$curEng2 = (int) $_POST("Eng2Key");
	$curMultX2 = (int) $_POST("MultX2Key");
	$curMultX3 = (int) $_POST("MultX3Key");
	$curMultX4 = (int) $_POST("MultX4Key");
//replace what's in the files with the unity variable except for username
	file_put_contents($xpFile, $curXp);
	file_put_contents($progressFile, $curProgress);
	file_put_contents($Dmg1File, $curDmg1);
	file_put_contents($Dmg2File, $curDmg2);
	file_put_contents($Dmg3File, $curDmg3);
	file_put_contents($Dmg4File, $curDmg4);
	file_put_contents($Dmg5File, $curDmg5);
	file_put_contents($Shd1File, $curShd1);
	file_put_contents($Shd2File, $curShd2);
	file_put_contents($Shd3File, $curShd3);
	file_put_contents($Shd4File, $curShd4);
	file_put_contents($Shd5File, $curShd5);
	file_put_contents($Hth1File, $curHth1);
	file_put_contents($Hth2File, $curHth2);
	file_put_contents($Hth3File, $curHth3);
	file_put_contents($HthNShd1File, $curHthNShd1);
	file_put_contents($HthNShd2File, $curHthNShd2);
	file_put_contents($HthNShd3File, $curHthNShd3);
	file_put_contents($HthNShd4File, $curHthNShd4);
	file_put_contents($HthNShd5File, $curHthNShd5);
	file_put_contents($HthNShd6File, $curHthNShd6);
	file_put_contents($HthStl1File, $curHthStl1);
	file_put_contents($HthStl2File, $curHthStl2);
	file_put_contents($HthStl3File, $curHthStl3);
	file_put_contents($HthStl4File, $curHthStl4);
	file_put_contents($HthStl5File, $curHthStl5);
	file_put_contents($ShdStl1File, $curShdStl1);
	file_put_contents($ShdStl2File, $curShdStl2);
	file_put_contents($ShdStl3File, $curShdStl3);
	file_put_contents($ShdStl4File, $curShdStl4);
	file_put_contents($ShdStl5File, $curShdStl5);
	file_put_contents($ReverseFile, $curReverse);
	file_put_contents($Eng1File, $curEng1);
	file_put_contents($Eng2File, $curEng2);
	file_put_contents($MultX2File, $curMultX2);
	file_put_contents($MultX3File, $curMultX3);
	file_put_contents($MultX4File, $curMultX4);
?>
